[versions]
# Plugins
kotlin = "2.4.20"
dokka = "2.2.0"
kotlinter = "5.4.2"
pluginYml = "0.6.0"
minecraftServer = "4.0.2"
shadow = "9.6.1"
mavenPublish = "0.35.0"
kover = "0.9.9"

# Libraries
paper = "1.16.5-R0.1-SNAPSHOT"
paper-mockbukkit = "1.21.11-R0.1-SNAPSHOT"
junit = "6.0.3"
mockbukkit = "4.109.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
pluginYml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginYml" }
minecraftServer = { id = "dev.s7a.gradle.minecraft.server", version.ref = "minecraftServer" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[libraries]
paper = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "paper" }
paper-mockbukkit = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-mockbukkit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
mockbukkit = { group = "org.mockbukkit.mockbukkit", name = "mockbukkit-v1.21", version.ref = "mockbukkit" }
